version: "3.7"
services:
        rest_easy:
                image: rest_easy:v1
                volumes:
                 - static:/static
                environment:
                 - PYTHONUNBUFFERED=1 #This allows you to view logs in terminal when running in attached mode
                 - DEBOUNCE=3 #How long between button presses to ignore- Default 3
                 - STANDARDLOGIC=True #If button input is high when pressed set to true- Default True
                 - ENABLELOGS=False #If you want a log file created with timestamps for each button press set to true- Default False
                 - BUTTONINPUT= 13 #Choose the input pin used to detect button press (BCM pinout) - Default 13
                devices:
                 - /dev/gpiomem:/dev/gpiomem
                dns:
                 - 192.168.1.1 #replace with your local dns to resolve .local host names
                 - 8.8.8.8
                 - 4.4.4.4
                restart: always
        configure_rest_easy:
                image: configure_rest_easy:v1
                ports:
                 - "80:5000" #Change first number to switch the port that config is served on
                volumes:
                 - templates:/templates
                 - static:/static # You can edit index.html and success.html if you want a custom look
                restart: always
        blackberrypi: #comment out or remove this service to keep LEDs on
                image: blackberrypi:v1
                volumes:
                 - /sys/class/leds/led0:/sys/class/leds/led0 #confirmed file path on Rpi zero w
                restart: always
volumes:
        static:
        templates:
